### ISSUE TITLE
Next release drops Ruby 2.7?

### ISSUE THREAD

**Issue by pboling** [dry-rb/dry-transformer#16]
According to the readme and the gemspec the next release of this gem appears to target Ruby >= 3, however, the next version of ROM, at version 6 will target Ruby >= 2.7, unless that has changed.  Was bumping past 2.7 a mistake?

If the next release drops ruby 2.7, will it be a major version bump to 2, following the spirit of SemVer?

**Comment by solnic** [comment]
ROM 6 will require Ruby >= 3.0. We're also dropping support for 2.7 in all dry-rb gems, but it won't need bumping major version numbers.
